[package]
name = "chess-bot"
version = "0.1.0"
edition = "2021"

[features]
log_to_file = []
uci = ["log_to_file"]
default = []

[dependencies]
num-traits = "0.2"
num-derive = "0.4"
num_enum = "0.5.0"
itertools = "0.13.0"
rand = "0.8.4"
log = "0.4"
env_logger = "0.10"
thiserror = "1.0"